name: CI
 
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
   inputs:
      namemu:
        description: 'What is your name'
        required: true

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Hay ${{ github.event.inputs.namemu }}
      run: ls
    - name: GIT CLONE
      run: git clone https://github.com/FRM-Developer/BaseSelfBot
    - name: PROCESS
      run: cd BaseSelfBot && npm install && npm start